embed_assets: on
package_path: packages
javascripts:
  default:
    - public/javascripts/application.js
    - public/javascripts/admin/jquery-1.5.js  
    - public/javascripts/admin/jquery-rails.js
stylesheets:
  default:
    - public/stylesheets/styles.css
